# Generated by Django 4.1.3 on 2022-11-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionAcudiente', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('nombresAcudiente', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidosAcudiente', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('parentescoAcudiente', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('ocupacionAcudiente', models.CharField(max_length=50, verbose_name='Ocupacion')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('lugarResidencia', models.CharField(max_length=50, verbose_name='Lugar de residencia')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion')),
                ('barrio', models.CharField(max_length=50, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefonoFijo', models.CharField(max_length=50, verbose_name='Telefono fijo')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('telefonoSecundario', models.CharField(max_length=50, verbose_name='Telefono secundario')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresFamiliar', models.CharField(max_length=50, verbose_name='Nombres del familiar')),
                ('apellidosFamiliar', models.CharField(max_length=50, verbose_name='Apellidos del familiar')),
                ('parentescoFamiliar', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('telefonoFamiliar', models.CharField(max_length=50, verbose_name='Telefono fijo o celular')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionPersonal', models.CharField(max_length=50, verbose_name='Identificacion')),
                ('nombresPersonal', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidosPersonal', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefonoPersonal', models.CharField(max_length=50, verbose_name='Telefono fijo o celular')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombresBeneficario', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidosBeneficiario', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='T.I.', max_length=5, verbose_name='Tipo de Documento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=15, verbose_name='Genero')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('estadoCivil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Union Libre')], default='Soltero', max_length=20, verbose_name='Estado Civil')),
                ('edad', models.CharField(max_length=50, verbose_name='Edad')),
                ('fechaNacimiento', models.DateField(help_text='DD/MM/AA', verbose_name='Fecha de nacimiento')),
                ('lugarNacimiento', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('estatura', models.CharField(max_length=50, verbose_name='Estatura')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso')),
                ('tipoSangre', models.CharField(max_length=50, verbose_name='Tipo de sangre')),
                ('eps', models.CharField(max_length=50, verbose_name='EPS')),
                ('tallaCamisa', models.CharField(max_length=50, verbose_name='Talla camisa')),
                ('tallaPantalon', models.CharField(max_length=50, verbose_name='Talla pantalon ')),
                ('tallaCalzado', models.CharField(max_length=50, verbose_name='Talla de calzado')),
                ('personasVive', models.CharField(max_length=50, verbose_name='No. personas con quien vive')),
                ('dedica', models.CharField(max_length=50, verbose_name='A que se dedica el beneficiario?')),
                ('colegio', models.CharField(max_length=50, verbose_name='Colegio')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('ingresosMensuales', models.CharField(max_length=50, verbose_name='Ingresos mensuales del nucleo familiar')),
                ('sisben', models.CharField(max_length=50, verbose_name='Categoria sisben')),
                ('estrato', models.CharField(max_length=50, verbose_name='Estrato')),
                ('viviendaPropia', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=15, verbose_name='Vivienda Propia')),
                ('servicioPublico', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=15, verbose_name='Servicios públicos')),
                ('servicioInternet', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=15, verbose_name='Servicio de internet')),
                ('programas', models.CharField(choices=[('Alimentarte', 'Alimentarte'), ('Formarte', 'Formarte'), ('Impulsarte', 'Impulsarte'), ('Bienestar', 'Bienestar'), ('Cuidarte', 'Cuidarte')], default='Alimentarte', max_length=20, verbose_name='Programas')),
                ('fechaInicial', models.DateField(help_text='DD/MM/AA', verbose_name='Fecha inicial')),
                ('estadoUsuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Retirado', 'Retirado')], default='Activo', max_length=20, verbose_name='Estado del beneficiario')),
                ('estadoCarnet', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Pendiente', 'Pendiente'), ('Inhabilitado', 'Inhabilitado')], default='Habilitado', max_length=20, verbose_name='Estado del carnet')),
                ('nombresPadrino', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidosPadrino', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('identificacionPadrino', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('telefonoPadrino', models.CharField(max_length=50, verbose_name='Telefono fijo')),
                ('celularPadrino', models.CharField(max_length=50, verbose_name='Celular')),
                ('correoPadrino', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('documentoAcudiente', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('registroCivil', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fotoBeneficiario', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('formato', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('autorizacion', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('tarjetaIdentidad', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('carnet', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('factura', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('DatosContacto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.datoscontacto')),
                ('ReferenciaFamiliar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.referenciafamiliar')),
                ('ReferenciaPersonal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.referenciapersonal')),
            ],
        ),
    ]
