# Generated by Django 4.1.1 on 2022-11-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='T.I.', max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='T.I.', max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('extranjero', models.BooleanField(default=False, verbose_name='Es extranjero?')),
                ('tipoSangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Tipo de Documento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15, verbose_name='Género')),
                ('fechaNacimiento', models.DateField(help_text='DD/MM/AA', verbose_name='Fecha de nacimiento')),
                ('lugarNacimiento', models.CharField(max_length=50, verbose_name='Lugar de Nacimiento')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('barrio', models.CharField(max_length=50, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('telefonoSecundario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono secundario')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='T.I.', max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Padrino_Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.padrino', verbose_name='Padrino')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('PASS', 'Pasaporte')], default='T.I.', max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('relacion', models.CharField(max_length=50, verbose_name='Relación')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('tipoReferencia', models.CharField(choices=[('T.I.', 'Personal'), ('R.C.', 'Familiar')], max_length=5, verbose_name='Tipo de Referencia')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='DatosContacto',
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='ReferenciaFamiliar',
        ),
        migrations.RemoveField(
            model_name='informacionpersonal',
            name='ReferenciaPersonal',
        ),
        migrations.DeleteModel(
            name='DatosContacto',
        ),
        migrations.DeleteModel(
            name='InformacionPersonal',
        ),
        migrations.DeleteModel(
            name='ReferenciaFamiliar',
        ),
        migrations.DeleteModel(
            name='ReferenciaPersonal',
        ),
        migrations.AddField(
            model_name='acudiente',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario'),
        ),
    ]
