# Generated by Django 4.1.3 on 2022-12-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_acudiente_beneficiario_padrino_padrino_beneficiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='tipoSangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Tipo de sangre'),
        ),
    ]
