# Generated by Django 4.1.1 on 2022-11-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_acudiente_beneficiario_padrino_padrino_beneficiario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Socio_Economico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=50, verbose_name='A que se dedica el beneficiario?')),
                ('colegio', models.CharField(max_length=50, verbose_name='Colegio')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('ingresos', models.CharField(max_length=50, verbose_name='Ingresos mensuales del nucleo familiar')),
                ('sisben', models.CharField(max_length=50, verbose_name='Categoria sisben')),
                ('estrato', models.CharField(max_length=50, verbose_name='Estrato')),
                ('viviendaPropia', models.BooleanField(default=False, verbose_name='Tiene Vivienda Propia?')),
                ('servicioLuz', models.BooleanField(default=False, verbose_name='Tiene Servicio de Luz?')),
                ('servicioAgua', models.BooleanField(default=False, verbose_name='Tiene Servicio de Agua?')),
                ('servicioGas', models.BooleanField(default=False, verbose_name='Tiene Servicio de Gas?')),
                ('servicioInternet', models.BooleanField(default=False, verbose_name='Tiene Servicio de Internet?')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Programas_Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, help_text='DD/MM/AA', verbose_name='Fecha de ingreso')),
                ('estadoUsuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Retirado', 'Retirado')], default='Activo', max_length=20, verbose_name='Estado del Beneficiario')),
                ('estadoCarnet', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Pendiente', 'Pendiente'), ('Inhabilitado', 'Inhabilitado')], default='Pendiente', max_length=20, verbose_name='Estado del carnet')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
                ('programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.programa', verbose_name='Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentoAcudiente', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('registroCivil', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('foto', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('formato', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('autorizacion', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('tarjetaIdentidad', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('carnet', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('factura', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Crecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura', models.CharField(max_length=50, verbose_name='Estatura')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso')),
                ('enfermedad', models.CharField(max_length=50, verbose_name='Enfermedad')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='Discapacidad')),
                ('eps', models.CharField(max_length=50, verbose_name='EPS')),
                ('tallaCamisa', models.CharField(max_length=50, verbose_name='Talla camisa')),
                ('tallaPantalon', models.CharField(max_length=50, verbose_name='Talla pantalon ')),
                ('tallaCalzado', models.CharField(max_length=50, verbose_name='Talla de calzado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
    ]
