# Generated by Django 4.1.3 on 2022-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
